### ISSUE TITLE
RabbitMQ 3.7.0 plugins_not_found

### ISSUE THREAD

**Issue by Meabed** [rabbitmq/rabbitmq-delayed-message-exchange#104]
on RabbitMQ 3.7.0 docker image "rabbitmq:3.7.0-management-alpine" When i try to enable the plugin i get the error message
Downloaded the plugin in the plugins folders 
```
/opt/rabbitmq/plugins
-rw-r--r--    1 root     root         42439 Nov 29 17:21 rabbitmq_delayed_message_exchange-3.7.0.zip
```
```
bash-4.4# rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Error:
{:plugins_not_found, [:rabbitmq_delayed_message_exchange]}
```

When listing plugins, it is not there as well 

```
bash-4.4# rabbitmq-plugins list

07:40:33.858 [error] ** System running to use fully qualified hostnames **
** Hostname 65ffa59a9ca5 is illegal **

 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: [failed to contact rabbit@65ffa59a9ca5 - status not shown]
 |/
[  ] rabbitmq_amqp1_0                  3.7.0
[  ] rabbitmq_auth_backend_cache       3.7.0
[  ] rabbitmq_auth_backend_http        3.7.0
[  ] rabbitmq_auth_backend_ldap        3.7.0
[  ] rabbitmq_auth_mechanism_ssl       3.7.0
[  ] rabbitmq_consistent_hash_exchange 3.7.0
[  ] rabbitmq_event_exchange           3.7.0
[  ] rabbitmq_federation               3.7.0
[  ] rabbitmq_federation_management    3.7.0
[  ] rabbitmq_jms_topic_exchange       3.7.0
[E ] rabbitmq_management               3.7.0
[e ] rabbitmq_management_agent         3.7.0
[  ] rabbitmq_mqtt                     3.7.0
[  ] rabbitmq_peer_discovery_aws       3.7.0
[  ] rabbitmq_peer_discovery_common    3.7.0
[  ] rabbitmq_peer_discovery_consul    3.7.0
[  ] rabbitmq_peer_discovery_etcd      3.7.0
[  ] rabbitmq_peer_discovery_k8s       3.7.0
[  ] rabbitmq_random_exchange          3.7.0
[  ] rabbitmq_recent_history_exchange  3.7.0
[  ] rabbitmq_sharding                 3.7.0
[  ] rabbitmq_shovel                   3.7.0
[  ] rabbitmq_shovel_management        3.7.0
[  ] rabbitmq_stomp                    3.7.0
[  ] rabbitmq_top                      3.7.0
[  ] rabbitmq_tracing                  3.7.0
[  ] rabbitmq_trust_store              3.7.0
[e ] rabbitmq_web_dispatch             3.7.0
[  ] rabbitmq_web_mqtt                 3.7.0
[  ] rabbitmq_web_mqtt_examples        3.7.0
[  ] rabbitmq_web_stomp                3.7.0
[  ] rabbitmq_web_stomp_examples       3.7.0
```

is it known issue or it need fix ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Either the directory you use is an incorrect one or the file is not readable. Anyhow, RabbitMQ cannot discover it.

**Comment by allan-simon** [comment]
as I found this issue by googling, here's the solution:

1. this specific plugins need to be downloaded first 

`wget https://dl.bintray.com/rabbitmq/community-plugins/3.7.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20171201-3.7.x.zip` and unzipped into the `plugins` directory of your rabbitmq installation, only then you can enable it :)

**Comment by Meabed** [comment]
Yes Thanks :) i didn't unzip it before. i figured it out was kinda of not so smart hehe :)

**Comment by innerpeacez** [comment]
i have same issue

![image](https://user-images.githubusercontent.com/37059529/56788184-53324380-6831-11e9-96df-4614e00cc59c.png)

![image](https://user-images.githubusercontent.com/37059529/56788243-7e1c9780-6831-11e9-9ebe-bc455ed9eab4.png)

but 

![image](https://user-images.githubusercontent.com/37059529/56788289-9ee4ed00-6831-11e9-997f-6788de556da1.png)

why ? please :(

**Comment by lukebakken** [comment]
@innerpeacez please use [the mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future.

You should run this command as documented:

```
rabbitmq-plugins enable rabbitmq_delayed_message_exchange
```
