### ISSUE TITLE
Working with RabbitMQ 3.7.2?

### ISSUE THREAD

**Issue by Fydon** [rabbitmq/rabbitmq-delayed-message-exchange#106]
When enabling the 3.7.x version of this plugin (obtain from [here][1]) on Windows 10 with Erlang 20.1 64bit, I see the following:

    & .\rabbitmq-plugins.bat enable rabbitmq_delayed_message_exchange
    Enabling plugins on node rabbit@MyPC:
    rabbitmq_delayed_message_exchange

    09:56:01.951 [error] 'File operation error: eacces. Target: c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez/ebin. Function: read_file_info. Process: code_server.'

    09:56:03.412 [error] 'File operation error: eacces. Target: c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez/ebin. Function: read_file_info. Process: code_server.'

    09:56:03.828 [error] 'File operation error: eacces. Target: c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez/ebin. Function: read_file_info. Process: code_server.'
    The following plugins have been configured:
      rabbitmq_delayed_message_exchange
      rabbitmq_management
      rabbitmq_management_agent
      rabbitmq_web_dispatch
    Applying plugin configuration to rabbit@MyPC...
    The following plugins have been enabled:
      rabbitmq_delayed_message_exchange

Messages are sending through the exchange and it appears that delay is working, but I don't know the implications of the above error.

[1]: https://www.rabbitmq.com/community-plugins.html

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
You cannot use a 3.6.x build of this plugin with a 3.7.x node. See [Community plugins](http://www.rabbitmq.com/community-plugins.html) which lists two separate downloads.

**Comment by Fydon** [comment]
@michaelklishin Sorry. Thank you for your response.

When I initially disabled the old version of the plugin, I had already copied the new version into the plugin folder:

    2018-01-12 09:54:32.633 [warning] <0.1270.0> Problem reading some plugins: [{"c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez",duplicate_plugin}]
    2018-01-12 09:54:33.405 [warning] <0.1270.0> Problem reading some plugins: [{"c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez",duplicate_plugin}]
    2018-01-12 09:54:33.461 [info] <0.1270.0> Stopping RabbitMQ applications and their dependencies in the following order:
        rabbitmq_delayed_message_exchange
    2018-01-12 09:54:33.461 [info] <0.1270.0> Stopping application 'rabbitmq_delayed_message_exchange'
    2018-01-12 09:54:33.469 [info] <0.33.0> Application rabbitmq_delayed_message_exchange exited with reason: stopped
    2018-01-12 09:54:33.543 [info] <0.1270.0> Plugins changed; disabled [rabbitmq_delayed_message_exchange]

I then deleted the old plugin and then enabled the new one:

    2018-01-12 09:54:52.989 [warning] <0.1296.0> Problem reading some plugins: [{"c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez",{invalid_ez,eacces}}]
    2018-01-12 09:54:53.644 [warning] <0.1296.0> Problem reading some plugins: [{"c:/PROGRA~1/RABBIT~1/RABBIT~1.2/plugins/rabbitmq_delayed_message_exchange-0.0.1.ez",{invalid_ez,eacces}}]
    2018-01-12 09:54:53.716 [info] <0.33.0> Application rabbitmq_delayed_message_exchange started on node rabbit@TDearhamPC2
    2018-01-12 09:54:53.716 [info] <0.1296.0> Plugins changed; enabled [rabbitmq_delayed_message_exchange]

I ran disable and enable a few times and it reported the access error. However now without restarting RabbitMQ disabling and enabling this plugin is working without error.

**Comment by michaelklishin** [comment]
Plugins are expanded (uncompressed) into a directory, so deleting an archive won't delete the actual modules loaded.

`EACCES` on Windows can mean that an anti-virus tool kicked in. On UNIX systems when
a file is recreated it can be [due to a very restrictive file mask](https://github.com/rabbitmq/rabbitmq-server/issues/1129). Neither of those things are under RabbitMQ's control.

This discussion belongs to the mailing list.

**Comment by michaelklishin** [comment]
So the node reports a

> duplicate_plugin

which means at some point there were two versions of this plugin on code path.
