### ISSUE TITLE
Cannot enable plugin

### ISSUE THREAD

**Issue by dgarstang** [rabbitmq/rabbitmq-delayed-message-exchange#107]
I am having exactly the same issue as this:
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/45

Ie, plugin has been downloaded and placed in the plugins directory:
```
[root@default-centos-7 ~]# ls -l /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.14/plugins/rabbitmq_delayed_message_exchange.ez
-rw-r--r--. 1 root root 29853 Feb  6 18:48 /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.14/plugins/rabbitmq_delayed_message_exchange.ez
```

Attempting to enable the plugin results in:
```
[root@default-centos-7 ~]# rabbitmq-plugins enable rabbitmq_delayed_message_exchange
Error: The following plugins could not be found:
  rabbitmq_delayed_message_exchange
```

RabbitMQ 3.6.4 is installed and running.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There isn't much we can suggestion without knowing where the file was downloaded from or server logs. I highly recommend making sure that the file has the same permissions and ownership as the plugins that ship with RabbitMQ, not `root:root` even if you make the file world readable.
