### ISSUE TITLE
Failed to add a new exchange

### ISSUE THREAD

**Issue by pqkhanh88** [rabbitmq/rabbitmq-delayed-message-exchange#108]
Hi,
I cannot add a new "x-delayed-message" exchange
I using version: 3.7.4
```
Request to node rabbit@92e61773d1d0 failed with {'EXIT',
{function_clause,
[{rabbit_exchange_type_delayed_message,
validate,
[{exchange,
{resource,
<<"virtual-host-1">>,
exchange,
<<"x-delay">>},
'x-delayed-message',
true,false,false,[],
undefined,undefined,
undefined,
{[],[]},
#{user =>
<<"adminuser">>}}],
[{file,
"src/rabbit_exchange_type_delayed_message.erl"},
{line,60}]},
{rabbit_exchange,declare,
7,
[{file,
"src/rabbit_exchange.erl"},
{line,170}]},
{rabbit_channel,
handle_method,5,
[{file,
"src/rabbit_channel.erl"},
{line,2271}]},
{rpc,local_call,3,
[{file,"rpc.erl"},
{line,321}]},
{rabbit_mgmt_util,
'-direct_request/6-fun-12-',
9,
[{file,
"src/rabbit_mgmt_util.erl"},
{line,769}]},
{rabbit_mgmt_util,
with_vhost_and_props,3,
[{file,
"src/rabbit_mgmt_util.erl"},
{line,814}]},
{cowboy_rest,call,3,
[{file,
"src/cowboy_rest.erl"},
{line,1128}]},
{cowboy_rest,
process_content_type,3,
[{file,
"src/cowboy_rest.erl"},
{line,938}]}]}} 

```

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
