### ISSUE TITLE
Remove dependency on rabbitmq_management_visualiser

### ISSUE THREAD

**Issue by jdubiner** [rabbitmq/rabbitmq-delayed-message-exchange#109]
Please remove the dependency on rabbitmq_management_visualiser, as it is no longer supported in the current version of rabbitmq...   I'm seeing the issue on version 3.7.4 installed on OSX with homebrew,

**Comment by michaelklishin** [comment]
There is [no such dependency](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/v3.6.x/Makefile#L5) in 3.6.x or master.

**Comment by sxjzank** [comment]
> There is [no such dependency](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/blob/v3.6.x/Makefile#L5) in 3.6.x or master, and never was.

i have a same error and I install rabbitmq with homebrew. Now I dont find how to  disable or offline  this plugin.
Please remove this dependency on homebrew ..

**Comment by michaelklishin** [comment]
@sxjzank the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rabbitmq.rb) (which our team does not maintain) does not enable this plugin. It can't: it hasn't shipped with RabbitMQ since 3.5.x, last updated [in November 2016](https://www.rabbitmq.com/changelog.html). You haven't provided any error messages or other specifics so I'll have to guess: you had a Homebrew installation back in the `3.5.x` days and the enabled plugins file still lists this plugin.

[The Enabled Plugins File](https://www.rabbitmq.com/plugins.html#enabled-plugins-file) and [Troubleshooting](https://www.rabbitmq.com/plugins.html#troubleshooting) provide some relevant information.

Uninstalling the formula and purging all of its `etc` files then resintalling should help.

**Comment by sxjzank** [comment]
> @sxjzank the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rabbitmq.rb) (which our team does not maintain) does not enable this plugin. It can't: the plugin hasn't shipped with RabbitMQ since 3.5.x, last updated [in November 2016](https://www.rabbitmq.com/changelog.html). You haven't provided any error messages or other specifics so I'll have to guess: you had a Homebrew installation back in the `3.5.x` days and the enabled plugins file still lists this plugin.
> 
> [The Enabled Plugins File](https://www.rabbitmq.com/plugins.html#enabled-plugins-file) and [Troubleshooting](https://www.rabbitmq.com/plugins.html#troubleshooting) provide some relevant information.
> 
> Uninstalling the formula and purging all of its `etc` files then resintalling should help.

Thx.I have removed this config in The Enabled Plugins File.
