### ISSUE TITLE
rabbitmq-server 3.7.5 crash on arch linux

### ISSUE THREAD

**Issue by sivanbecker** [rabbitmq/rabbitmq-delayed-message-exchange#112]
Hi, 

I'm working with Celery and Rabbitmq on arch linux for quite a long time and in the last few days i started getting this crash report when ever i start rabbitmq-server

=CRASH REPORT==== 3-Jul-2018::10:12:24.612692 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.109.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.99.0>]
    message_queue_len: 0
    messages: []
    links: [<0.102.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 234
  neighbours:

did anyone encounter this ?
what other info do you need to debug ?

thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You are almost certainly running on [Erlang/OTP 21 which is not supported by RabbitMQ 3.7.5](https://github.com/rabbitmq/rabbitmq-server/issues/1616).

**Comment by michaelklishin** [comment]
The docs [suggest as much](http://www.rabbitmq.com/which-erlang.html).

**Comment by sivanbecker** [comment]
Thanks Michael, indeed erlang version. solved it using [this url](https://bugs.archlinux.org/index.php?do=details&task_id=59112&action=details.add_notification&ids=59112&user_id=28160)

Next time will use the google forum. :)
