### ISSUE TITLE
X-delay greater than 24 hours

### ISSUE THREAD

**Issue by jeromepissis** [rabbitmq/rabbitmq-delayed-message-exchange#122]
I try to add a delay to my RabbitMQ Job. It's work fine with delay < 24h but if the delay is greater than 24h, the job disapear and it doesn't execute.

I setup x-delay like that :

[
    'x-delay'    => $delay_milisec,
    'execute_at' => $execute_at->format('c')
]

I try that but is the same..

[
    'x-delay'    => $delay_milisec,
]

Many thanks for your help

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin has a delay limit of `2^32-1` milliseconds (an Erlang timer limitation), which is [documented](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#performance-impact). That's about 49 days.

Client libraries may effectively place additional restrictions but I don't know much about PHP or the client used to suggest much. 24 hours is between `2^26` and `2^27` milliseconds. That doesn't ring any bells when it comes to heards and AMQP 0-9-1 table value types.

**Comment by jeromepissis** [comment]
Thanks for your reply.
I would check that
