### ISSUE TITLE
Fail to compile from sources: can't find include lib "rabbit/include/amqqueue.hrl"

### ISSUE THREAD

**Issue by Bacto** [rabbitmq/rabbitmq-delayed-message-exchange#151]
Hi,

I have tried to compile the plugin from sources but it fails.

```bash
git clone https://github.com/rabbitmq/rabbitmq-delayed-message-exchange.git
cd rabbitmq-delayed-message-exchange
git checkout -b 3.8.9
make dist
```

Then I get the error `src/rabbit_federation_util.erl:10: can't find include lib "rabbit/include/amqqueue.hrl"`.

With the tag v3.8.0 the same commands work with no error.

With no certitudes, I have tried to fix the DEPS_DIR with `DEPS_DIR=deps make dist`.
It seems to go further but fails on `src/amqp_gen_consumer.erl: undefined parse transform 'lager_transform'`.

Is this a bug or did I missed something with the compilation method?

**Comment by michaelklishin** [comment]
RabbitMQ has made a major change to the development workflow a few days ago: now instead of an [umbrella repository](https://github.com/rabbitmq/rabbitmq-public-umbrella) all sub-projects reside in a [single monorepo](https://github.com/rabbitmq/rabbitmq-server). For 3rd party and community plugins such as this one, it means that it has to be cloned under the `deps` directory there. This may change soon, how exactly such plugins will have to adapt is yet to be decided.

There should be no reason to build this plugin from source. We have just [produced a new release for RabbitMQ `3.8.9`](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/tag/3.8.9) (technically `3.8.5`+ but you really should upgrade). It supports Erlang 22.3+ and addresses an incompatibility with core broker changes since `3.8.0`.

**Comment by michaelklishin** [comment]
I can reproduce and confirm that an "umbrella style" build where the plugin is cloned under `deps` in the `rabbitmq/rabbitmq-server` repository (the new monorepo) succeeds:

``` shell
gmake; gmake dist
```

This produces a build against `master`, which is likely not what you are looking for. At the very least you should switch the branch to `v3.8.x` in both repos. I am yet to try this as I don't think the `v3.8.x` migration for the monorepo is complete at the moment.

This also won't produce an `.ez` file you are likely looking for: `gmake dist` no longer does that without additional options. I'd have to find what the Make variable is.

All in all, you are much better off not building this plugin from source in the next few weeks, and in general. Just use the provided binary builds distributed via GitHub releases.

**Comment by Bacto** [comment]
Thanks for all these informations Michael!
I will use the binary build for now but I hope in the near future we will be able to compile it directly from sources :)
