### ISSUE TITLE
No metrics for exchange publish out (count nor rate)

### ISSUE THREAD

**Issue by annieblomgren** [rabbitmq/rabbitmq-delayed-message-exchange#157]
Tested in RabbitMQ version 3.8.12 Erlang 23.1 rabbitmq_delayed_message_exchange plugin 3.8.9.0199d11c

When publishing a delayed message to a delayed exchange no metrics for publish (out) is registered, neither when published nor routed later. Metric for publish (in) is there. 
Have checked that messages are being routed to a queue after the delay period.
Have tried with setting rates_mode to detailed but no difference. 

When publishing to a built-in exchange metrics are there.

**Comment by michaelklishin** [comment]
As discussion in https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/pull/197 explains, this exchange is such an outlier compared to other types that it has to do some of the work channels do in order to maintain metric tables. At the same time, it does not have access to the context that actual channels have.

So either very sensitive core RabbitMQ interfaces have to change because of this exchange, or this exchange would leak resources, or this issue is unresolvable as is.
