### ISSUE TITLE
Ability to edit and remove delayed messages

### ISSUE THREAD

**Issue by gholol** [rabbitmq/rabbitmq-delayed-message-exchange#16]
Hi

I really like your plugin but the lack of an option to view and what's more important remove delayed messages prevents  me from using it. Do you have any plans of implementing it?

**Comment by videlalvaro** [comment]
Having something like this would demand implementing a frontend to the Mnesia database, why don't you just ignore the messages you don't want/need?

BTW, the same case happens with RabbitMQ, where there's no queue peek/browse.

**Comment by michaelklishin** [comment]
If you want that ability, you want a data store. RabbitMQ is not really a data store.

**Comment by nd2s** [comment]
I'd also like to be able to remove delayed messages (like purging a queue). Reason:

I'm using it to delay "requeued" messages that failed (I'm putting failed messages into the delayed exchange with `x-delay` header set instead of NACKing them). But sometimes I've got a batch that I don't want to fix but just get rid of. Currently the only solution seems to be to delete the whole exchange.

**Comment by anilcrk** [comment]
thank you

**Comment by anilcrk** [comment]
> For the poor souls facing the same issue. Deleting and recreating the exchange is not enough, delayed messages will still be delivered. The only trick is to disable and re-enable the plugin:
> 
> ```
> rabbitmq-plugins disable rabbitmq_delayed_message_exchange
> rabbitmq-plugins enable rabbitmq_delayed_message_exchange
> ```
> 
> As says the readme,
> 
> > **ALL DELAYED MESSAGES THAT HAVEN'T BEEN DELIVERED WILL BE LOST.**
> 
> Which is precisely what we want here 👌

successful 👌
