### ISSUE TITLE
Status of this plugin

### ISSUE THREAD

**Issue by TheCelavi** [rabbitmq/rabbitmq-delayed-message-exchange#77]
First article about this plugin that I have found is from first half of Y2015: https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

It states: "We have released the plugin as experimental..."

Question: Is this plugin still experimental? Is this plugin going to have a long term support? Can we consider this as stable release? Can we depend on this plugin and plan our development accordingly?

Thank you! 

BTW - really appreciate what you guys are doing, thank you!

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
Have you considered searching list archives or GitHub issues before asking this? https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/65 and https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/issues/72 provide a pretty up-to-date picture.

This plugin had a few issues and one fundamental problem fixed in its first year-or-two of existence. #72 identifies fairly demanding use cases where the current architecture cannot support.

Otherwise it works OK for many. We would like to improve it to the point that it can accommodate #72 some day but it's far from being a priority for our small team. I don't think this plugin is commercially supported at the moment but it doesn't mean that it will be abandoned.

So, give it a try with your workload and decide for yourself.

**Comment by TheCelavi** [comment]
No, I didn't, I took a look to current issues.

In general - seams stable and working with some limitations, mainly considering a number of delayed messages.

Thanks. I still do believe that maybe some kind of note in README could be added...

**Comment by michaelklishin** [comment]
@TheCelavi we'd be happy to accept a pull request that updates the README but we need to be careful about what it says. In my mind this plugin is still experimental but that doesn't mean it's unstable or not useful.

I filed #78 for that.

**Comment by michaelklishin** [comment]
@TheCelavi no worries, although this is just a README update ;) We'll take care of it.

**Comment by TheCelavi** [comment]
Thank you!
