### ISSUE TITLE
Unusable system after crash

### ISSUE THREAD

**Issue by ctheune** [rabbitmq/rabbitmq-delayed-message-exchange#90]
Hey,

we're running the plugin and today the Linux VM experienced a crash with a storage outage and an unexpected KVM host reboot. After that rabbitmq instance recovered fine by itself and the application was humming away, except that messages that passed through a delayed exchange (and had the x-delay header set) would not appear anywhere. They looked like they went somewhere, but they didn't. When publishing a message on the exchange manually through the management UI everything was fine, except when we set the x-delay header. The management responded with "message published, but not routed". We then tried uninstalling the plugin, deleting the exchange, all back and forth multiple times, but to no avail.

We did not manage to get any indicative output from the rabbitmq instance's log.

At that point we decided to stop rabbitmq, delete the mnesia folder and start from scratch. And voila: that got it working again.

Our environment:

* Linux 4.4.59
* erlang-18.0
* rabbitmq-server-3.6.5

I have the old mnesia folder around in case that might have data that is interesting to you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions fofor potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
A "storage outage"  is not specific enough but this plugin (or anything in the VM) cannot guarantee that it could write any data to disk during that time.

Another possible scenario is mentioned in [plugin limitations](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#limitations): there may or may not be any queues to route delayed messages to, e.g. because the queues were exclusive or non-durable and thus didn't survive node restart.

There isn't any information which would prove any of the above right or wrong, so this is definitely mailing list material.
