### ISSUE TITLE
Purged Queues still receive delayed messages

### ISSUE THREAD

**Issue by amcdnl** [rabbitmq/rabbitmq-delayed-message-exchange#92]
I have the follow use case:

> A user creates a job with a cron schedule. The cron is translated to milliseconds and sent off as a delayed message. The user then goes back and updates the job to have a different time. The previously scheduled job should be canceled.

In order to accomplish this, I've tried both purging the queue and deleting the queue and exchange entirely to which no luck. Here is a gist of my code of which I'm doing to accomplish this:

```javascript
function startQueue(queueName) {
  await ch.assertQueue(
    queueName,
    { durable: true },
    { noAck: false });

  ch.consume(queueName, (msg) => {
   // reinvoke the job
    ch.publish(
        'delay-exchange',
        queueName,
        new Buffer(json),
        { headers: { 'x-delay': msg.content.nextTime } });
  }, { noAck: false });

  await ch.assertExchange('delay-exchange', 'x-delayed-message', {
    autoDelete: false,
    durable: true,
    passive: true,
    arguments: {
      'x-delayed-type': 'direct'
    }
  });

  ch.bindQueue(queueName, 'delay-exchange', queueName);
}

function startJob(time, queueName, json) {
  ch.publish(
    'delay-exchange', 
    queueName, 
    new Buffer(json), 
    { headers: { 'x-delay': time } 
  });
}

function stopJob(queueName) {
  await ch.assertQueue(
    queueName,
    { durable: true },
    { noAck: false });

  await ch.deleteQueue(queueName);
}
```

I'm wondering if the delayed message is working as intended in such it is sent off and doesn't care about the queue being deleted as long as its there when its ready?

Forgive me if this is duplicate of #89 or #16 ...

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Purging a queue does not prevent publishing to it. Deleting a queue will unless it's redeclared. This plugin is entirely unaware of both operations. It publishes to the target exchange with the provided routing key, the rest is no different from a message published any other way.

**Comment by amcdnl** [comment]
@michaelklishin - Thanks for your time, thats what I thought after investigation just wanted to confirm.
